return {
    {Name='souljaboy199',Reason='FMer'},
    Name='Sora295',Reason='Banned.'},
    {Name='iiDeadzone',Reason='FMer'},
    {Name='Avery348',Reason='FMer'},
    {Name='LegendOfDarknees',Reason='FMer'},
    {Name='BigNob',Reason='FMer'},
    {Name='acecateer',Reason='FMer'},
    {Name='Control22',Reason='FMer, Thinks hes protected but isnt.'},
    {Name='TheTrueRias',Reason='FMer'},
    {Name='xXDefeatedSoulsXx',Reason='FMer'},
    {Name='oldprince',Reason='FMer'},
    {Name='planedriver1',Reason='FMer'},
    {Name='HyperstrikeGamer',Reason='FMer'},
    {Name='thedeathstroke2',Reason='FMer and Pervert'},
    {Name='iiAustinM',Reason='Skid'},
    {Name='xxcoolboy8',Reason='Skid'},
    {Name='Conmiro',Reason='Skid'},
    {Name='Setolo',Reason='Skid'},
    {Name='anthony123459',Reason='Skid'},
    {Name='lilwayn4567',Reason='Begger and Leaker'},
    {Name='JrCamen',Reason='Dumb Lier and Scrub'},
    {Name='devinbur12350',Reason='Skid'},
    {Name='cameron36522',Reason='Stalker'},
    {Name='PrinceOfHeaven',Reason='Skid'},
    {Name='KingLoneCat',Reason='Skid'},
    {Name='iiVisualNightmareHD',Reason='Skid'},
    {Name='DarkLordMaster678',Reason='ODer that wont stfu up'},
    {Name='bryanperalta123',Reason='ODer that wont stfu up'},
    {Name='Obi1Shinobi',Reason='FMer'},
    {Name='iiShockzz',Reason='Annoying skid'},
    {Name='imreallytimlake2alt',Reason='Annoying skid'},
    {Name='christianwegnercw',Reason='Annoying skid'},
    {Name='noobkilervip',Reason='Shuts down servers and acts like a bigshot'},
    {Name='sonicboy12366',Reason='Loop respawns'},
    {Name='death124r',Reason='Skid & Derek1017\'s Sidekick'},
    {Name='Joshie0707',Reason='Editing Gravity 4.0'},
    {Name='NikePro2004',Reason='Stealing Credit for Prometheus'},
    {Name='playerpointclan',Reason='FMing idiot/banning everyone'},
    {Name='ClockworkHorror',Reason='FMing idiot'},
    {Name='Derek1017',Reason='FMing Idiot who got Hacked and has a Nice House'},
    {Name='marcoantoniosantos3',Reason='HUGE annoying noob'},
    {Name='nmoom1',Reason='HUGE annoying noob'},
    {Name='meunumbertwo',Reason='Skid/Lagging Server\'s/Etc'}, 
    {Name='Copenricus45',Reason='Alt of meunumbertwo'},
    {Name='lolman8776',Reason='Alt of meunumbertwo'},
    {Name='billwa25',Reason='Alt of meunumbertwo'},
    {Name='IchiMugFullDragon',Reason='Alt of meunumbertwo'},
    {Name='Kufarscum',Reason='Alt of meunumbertwo'},
    {Name='pein55',Reason='Alt of meunumbertwo'},
    {Name='TESTACCOUNT66666666',Reason='Alt of meunumbertwo'},
    {Name='M1sterJerk',Reason='Alt of meunumbertwo'},
    {Name='iOrbU',Reason='Alt of meunumbertwo'},
    {Name='ChickenYummyTummy',Reason='Alt of meunumbertwo'},
    {Name='TacticalOsama',Reason='Alt of meunumbertwo'},
    {Name='dewman2004',Reason='Alt of meunumbertwo'},
    {Name='ilovekaitlynnweber',Reason='Alt of meunumbertwo'},
    {Name='untitled5',Reason='Alt of meunumbertwo'},
    {Name='NewConstruction',Reason='Alt of meunumbertwo'},
    {Name='blakeblk',Reason='FMing Scrub who steals credit'},
    {Name='TheMcCoolguyKills',Reason='FMing Begging llittle Scrub'},
    {Name='KeroroGunso2016',Reason='Can\'t learn that the Script Bot doesn\'t work'},
    {Name='swordmaster7359',Reason='Racist'},
    {Name='SeiranXL',Reason='Annoying FMer who seems to not get the concept of learning to script'}
}
